wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1672932908.672402
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.8.15
      5: 0.13.7
      8:
      - 3
      - 5
